### PR TITLE
Add AudioSpheres to Indoor Audio Tour.

### PR DESCRIPTION
**Pull request by Zach777**
Resolves issue #342 .

 It adds AudioSpheres.

### CODE REVIEW

**Comment by Reousa** [comment]
@briligg audio sphere changes good to go?

**Comment by Zach777** [comment]
@Moonwards Right now the Interactor is not working with the player. I will make a PR for that and let you know when you can check it.

**Comment by Zach777** [comment]
@Reousa Please merge my Interactor PR first as it has the necessary changes for audio tour to work.

**Comment by Reousa** [comment]
> @Reousa Please merge my Interactor PR first as it has the necessary changes for audio tour to work.
Done 👌

**Comment by Zach777** [comment]
@Moonwards You can check out the AudioSpheres. I still need to get stairs to work with Interactor. Thus the intended audio tour route is not functional right now.

**Comment by Zach777** [comment]
@Moonwards The outdoor audio tour nodes are not named to match their respective audio. Please change the names of the Outdoor audio tour markers to match their respective audio.

**Comment by Moonwards** [comment]
@Zach777  I just checked and they all look right. `Audio_Tour_Outdoor_0` has to wait on the rover being all set up, so that it can be placed inside the Ground Passenger Pod that players ride in for the outdoor segment. Markers 1 through 11 all look to be in the right place.

**Comment by Zach777** [comment]
Where does Outdoor intro go?

**Comment by Moonwards** [comment]
Ah - it's one of the ones that plays between places. It's name doesn't make that clear. Because of the distance between the last indoor marker and the Passenger Pod docked in the Airlock Bay, I figured it could be triggered on the way, like maybe when you enter the Airlock Bay. Following the line on the ground should take you there, so I guess that's clear enough and using a trigger like that would work.

**Comment by Zach777** [comment]
@Moonwards Can you look at the add-audio-spheres branch and see the AudioSphere animations? Anything else you want me to add to AudioSpheres?

**Pull request merged**
