### PR TITLE
Windows of Center Atrium and in Atrium of First Atrium reflect Earth

### LINKED ISSUE #338: Reflection of Earth in mirrors of Hexpane Windows
image

The purpose of these window wells is that they reflect in the Earth. Currently they only reflect the sky, 
[Mirror-Reflecting-Earth.blend](https://app.gitkraken.com/api/glo/boards/5e96433deb480d00123f5d87/attachments/5f75f6436ddf5200112638a9)

### PR DESCRIPTION
**Pull request by Moonwards**
Resolves #338 

It doesn't need testing. I went to the windows in game and they are working fine, reflecting the Earth in the mirror as intended. Ready to merge.

### CODE REVIEW

**Comment by Moonwards** [comment]
Regarding the conflict with MoonTownMaster in the last commit, it looks like the code relevant to the mirrors is in the first 5 chunks shown in the diff, and the rest is changed ids. I tried looking at it with the thought of rebasing it myself. I hope this merge isn't very difficult because I'd really like this merged.

**Comment by Reousa** [comment]
@Moonwards Needs another QA pass as it was merged into.

**Comment by Moonwards** [comment]
The reflection feature is no longer there after the merges. It was overwritten somewhere.

**Comment by Reousa** [comment]
> The reflection feature is no longer there after the merges. It was overwritten somewhere.

I'll go over it again

**Comment by Moonwards** [comment]
Yes, this works now. Ready to merge.

**Review by Reousa — APPROVED** [review]

**Pull request merged**
