### PR TITLE
MASSIVE: Re open every tscn file once to force update to 3.1.1 specs

### PR DESCRIPTION
**Pull request by TheDuriel**
Hopefully fixes all seemingly "random" changes in files every time you pull and open the project.

I just did this with 3.1.1.stable.official specifically commit 66baa3b. Which is the official release of 3.1.1.

https://github.com/godotengine/godot/releases/tag/3.1.1-stable

### CODE REVIEW

**Comment by TheDuriel** [comment]
It's a bit worry some that theres 4000 lines missing now. Definitely needs testing before merging.

**Comment by TheDuriel** [comment]
This won't be merged until current WIP PRs are dealt with.

I highly encourage others to pull down my branch and try running this. So we can make sure it works.

**Comment by MolbOrg** [comment]
on my side with look fine with 3.1.1.stable.official, but there are some not tscn related stuff to fix
so I would recommend merging the patch, to level the field, it is one of the safest changes so far

**Comment by briligg** [comment]
It's hard to really be sure I've opened all the .tscn files, there's so many of them. I searched for .tscn to have it show as a list, but still.

When I run the game, the main menu loads. Then when I click 'Join Server', it hangs with this error

image

If I instead click 'Custom Game' the pop-up menu appears and I can select SinglePlayer, but it hangs with a silent error. If I instead select Host, it hangs with this error

image

I am not at all sure the game was working before this, though.

**Comment by briligg** [comment]
Yes, it lists identical errors for the current commit of the project master branch.

**Comment by TheDuriel** [comment]
Confirmed to be unrelated in #74 

I'll leave this open ti'll i wake up tomorrow, which will be well before any of you are around, then merge ;P

**Pull request merged**
