### PR TITLE
Adjust Billboard menu #709

### LINKED ISSUE #709: Change arrows on the Billboards
Navigating using the current arrows requires turning the camera a lot. Also, at this size, the arrow icons don't work that great. 

I'd like to move the arrows to the center above the text, and change them to more traditional triangle arrows used in music apps.

A space would need to be created for the arrows, or they can be overlaid on the bottom of the image, on a transparent black background.

### PR DESCRIPTION
**Pull request by Zach777**
resolves #709 

@Moonwards Let me know if you still want the arrows changed. I figured I should let you look at it first.

Also, I made the rich text field wider too.

### CODE REVIEW

**Comment by Moonwards** [comment]
Yes, please change the arrows.

**Comment by Zach777** [comment]
@Moonwards Please check the arrow buttons to see if that is satisfactory.

**Review by Moonwards — COMMENTED** [review]
The new arrows look good. I like the feel of the click effect. I tweaked the margins a little to give more room around the arrows. 

The area behind the text was translucent black before. Now it's just clear. I think that makes it a  little harder to read. Was that intentional?

**Comment by Zach777** [comment]
Tbh I don't know why that got changed.

**Comment by Moonwards** [comment]
Looks like another instance of colors changing for unknown reasons then. See if you can get it back, then, please.

**Comment by Zach777** [comment]
For some reason the mouse no longer works on any clickable. See #734

**Comment by Zach777** [comment]
The cause of the issue is the same between this issue and #739 . Help is blocking them somehow.

**Review by Moonwards — APPROVED** [review]
This is fine

**Pull request merged**
