### PR TITLE
Fix Rover dismount #635

### LINKED ISSUE #635: Game crashes when dismounting the Athlete Rover
@Zach777 to reproduce:
1. Mount the rover
2. Dismount the rover
Both using the interacts menu

### PR DESCRIPTION
**Pull request by Zach777**
Easy fix. Only changes InteractorComponent.gd

resolves #635

### CODE REVIEW

**Review by Reousa — CHANGES_REQUESTED** [review]
There is significant lag when dismounting the rover, that didn't exist before.

**Comment by Moonwards** [comment]
I confirm a strangely long lag when dismounting.
There is also an issue with the Interacts menu, in that when you dismount, it continues to be there, offering the option to take control of the rover although that isn't possible.

Screenshot from 2020-10-08 11-02-19

**Comment by Moonwards** [comment]
Also you can't dismount with F, you have to use E.

**Comment by Zach777** [comment]
I remember always having lag when dismounting the rover?

**Comment by Zach777** [comment]
Fixed the text bug. 
 I don't know what could be causing the Rover lag glitch. Maybe something to do with Lod?

**Review by Reousa — APPROVED** [review]
Confirmed the lag being LOD related.

**Pull request merged**
