### PR TITLE
Add Npc Editor

### LINKED ISSUE #269: Develop NPCs
A variety of NPCs are meant to be added over time, some of them quite complex. This is an area where a highly adaptable framework is important. The aim is to create a system that allows contribution of modified NPCs by advanced users down the road.

Initially the goal is simply to have a few NPCs just walking around, either in set loops or with path-finding behaviors. They should exist in First Gallery, the RecHab, Center Atrium, First Atrium, Rim Arcade, Teacup Crater, and the Spaceport. As objects and animations are added, they will need to be updated with increasingly complex behavior. 

Character models need to be made for them, at first they can be simple player models with different colors.

Attaching audio clips to the NPCs would be the next step. Some intro clip should play when a player is within a certain distance, and then further clips will play if the player follows the NPC, or interacts with a relevant object, or in some cases just remains near enough.

Moving to a full deployment of this would depend on having details modelled that allow an NPC to act out having a life in the town in some capacity - tending crops, overseeing construction, handling cargo, a doctor, things like that.

### PR DESCRIPTION
**Pull request by Zach777**
Do not merge until @yaelatletl Gives the approval.

resolves #269

### CODE REVIEW

**Comment by Zach777** [comment]
Would this PR address #269 ?

**Comment by Reousa** [comment]
> Would this PR address #269 ?

More or less yes, it's supposed to serve as a start for us to continue working on.

**Comment by Zach777** [comment]
So I should mark the PR as resolving #269 ?

**Comment by Reousa** [comment]
Yes, we'll refactor that issue after this is merged

**Comment by yaelatletl** [comment]
I wouldn't say the PR resolves #269 yet, only partially. it's the base for resolving that issue, but there's still code that needs to be done to get until that point.

**Pull request merged**
