### PR TITLE
A set of revisions to models and materials

### PR DESCRIPTION
**Pull request by Moonwards**
This is a collection of changes that would normally be done in a series of PRs

* The Road in Moon Town Master is widened
* Shader materials are set up in Second Gallery, Long Dome, and Teacup Crater
* The Road in Spaceport is widened
* Lalande Crater is altered in spots to match the changed roads
* Walls of Factory meshes are thickened
* A floor material is created in Center Atrium

### CODE REVIEW

**Comment by Reousa** [comment]
Merging this now, please verify it was merged properly on master @Moonwards

**Comment by Moonwards** [comment]
The Passenger Pod in the post-merge master branch is displaying as LOD2 no matter the distance of the player

**Comment by Reousa** [comment]
We no longer have distance based LOD, it has to be set through a DVT

**Comment by Moonwards** [comment]
True, i misspoke. Editing

**Pull request merged**
