### PR TITLE
Issue #111: New game server

### PR DESCRIPTION
**Pull request by SiudaPL**
Server Git ignores

### CODE REVIEW

**Comment by TheDuriel** [comment]
please refactor to use the _EXPORT/ directory as described in #49

the naming scheme should be:

`_EXPORT/server-<OS>/`

**Comment by TheDuriel** [comment]
please refactor to use the _EXPORT/ directory as described in #49

the naming scheme for server builds should be:

`_EXPORT/server-<OS>/`

**Comment by SiudaPL** [comment]
`_EXPORT/server-<OS>/`? I believe server is always Linux, at least the one we are going to use.

I think we can stay with `_server` as I created - all those exports are only unnecessary distraction while working on server. The server is a thing of it's own kind - you will need a Godot's server version and create a server process down there. It is not a file-storage only directory which `_exports` seems to be.

Also there is no need for everyone to have that directory. I created that one for server since it is pulling the game changes from GitHub. The ignores will keep working files out of the way.

**Comment by TheDuriel** [comment]
Exporting a server build for local testing is something we should expect and anticipate. All exported binaries should be located in the same structure.

Running the server, should not be done from the project directory whatsoever. (Except for local testing.)

For CI, and automatic builds _on_ the webserver, the output directory should not be located within the project directory. As I can't see how that would make things easier to manage.

**Comment by TheDuriel** [comment]
Still waiting on the requested changes.

**Comment by TheDuriel** [comment]
For example, this is the current structure.

image

While i did note make the folders, they might need changing, server exports will follow the structure.

server_64_<OS>

with a .git_keep file in the directory.

**Comment by SiudaPL** [comment]
Added requested directories in new PR: #132

**Comment by TheDuriel** [comment]
obsolete. i am adding the folders, and correcting the gitignore, as part of the LFS refactor.

**Pull request closed without merging**
