### PR TITLE
Create new assets and layout for main HUD and Building App UI.

### LINKED ISSUE #569: Rework main HUD design
An image of the current state of the draft will be updated here. This is further to #544. The section of the GDD is https://github.com/moonwards1/Moonwards-Virtual-Moon/wiki/User-Interface

Top left objects are finalized but may be tweaked visually  - in-game time, in-game location, friends online, and inbox.
Also bottom left - chat interface.

1 Map 
2  Building app
3. Library app
4. Events app
5 NPC app
6 Graphic novel app
7 Filming app
8 Collaborative building app

That was the intended list of apps, all of them need extensive development of their own. The Map is the easiest and clearest one, and the only one that isn't an app of its own that needs its own HUD and amounts to an entire gameplay mode.

### PR DESCRIPTION
**Pull request by Moonwards**
These commits create the graphics and layout for these user interfaces. They have been prepped to be programmed.

Closes #569, #570, #571.

### CODE REVIEW

**Comment by Reousa** [comment]
@Zach777 @Moonwards This LGTM. Can we get a final QA pass (I rebased it) to make sure nothing is broken?

**Review by Reousa — APPROVED** [review]

**Comment by Moonwards** [comment]
The new icons and layout is all there, as far as I can see. That's it for me really.

Any tweaking can wait for after the code is done for it.

**Comment by Zach777** [comment]
@Reousa Good to go. Anything in particular you needed me to check.

**Comment by Zach777** [comment]
List of things that were tested in QA. All approved

Vertical Stairs
Rover
Free Camera
3rd person
1st person
Human flight
Human movement
Hud menus in question
Chat
Airlock doors
Clickables

**Review by Zach777 — APPROVED** [review]

**Pull request merged**
