### PR TITLE
Fixes navigation issues around the ramp to the pool

### PR DESCRIPTION
**Pull request by yaelatletl**

### CODE REVIEW

**Comment by Moonwards** [comment]
How can this be tested?

**Comment by yaelatletl** [comment]
You can wait for an npc to go to that area and see they now won't get stuck

**Comment by Moonwards** [comment]
So they do get there? I tried going there and never saw anyone. Maybe I need to get there faster.

**Comment by yaelatletl** [comment]
There's an Anto NPC going there and also an Steve that goes out of there, but yes you should use fly mode to get there

**Comment by Moonwards** [comment]
Alright I've seen them both now. Yep, working fine.

**Review by Moonwards — APPROVED** [review]

**Pull request merged**
