### PR TITLE
Refactor/make humanoid epi

### PR DESCRIPTION
**Pull request by Zach777**

### CODE REVIEW

**Comment by Moonwards** [comment]
@Zach777 When I switch into first person mode, my avatar is invisible when I switch back out. It looks like the associated error is one that was showing up previously too -
 E 0:00:09.712   get_node: (Node not found: "../../Astronaut/Model/Female_Player/Skeleton/FemaleBody-LOD0" (relative to "/root/world/Navigation/NavigationMeshInstance/Moon_Town_Master/Marker_all_Constructs/Empty_STEMP-Facilities/STEMP_Facilities/MMC-BoatRads-STEMP/Android Depot/AndroidDepot/Holder/AndroidParent3/Android/ModelComponent").)
  <C++ Error>   Condition "!node" is true. Returned: __null
  <C++ Source>  scene/main/node.cpp:1371 @ get_node()
  <Stack Trace> ModelComponent.gd:8 @ _ready()
                SceneManager.gd:32 @ _change_scene()
                SceneManager.gd:26 @ _on_scene_ready()
                ResourceThreadedLoader.gd:30 @ load_async()

**Comment by Zach777** [comment]
@Moonwards I do not see this issue when running the game.

**Comment by Moonwards** [comment]
@Zach777 Alright, it doesn't happen on my Windows laptop, so let's ignore this new ghost issue that happens only on my Ubuntu Desktop.
Otherwise, I could find not issues, everything seems to work properly.

**Review by Moonwards — APPROVED** [review]

**Review by Moonwards — COMMENTED** [review]
Hate to say it, but I've now reproduced the invisible avatar issue in Windows. I've done so a couple of times. 


https://user-images.githubusercontent.com/50932660/126017591-eea53a3c-e094-44d1-a059-28471b350083.mp4

**Pull request merged**
