### PR TITLE
Restructure

### PR DESCRIPTION
**Pull request by TheDuriel**
Draft PR. Made to track progress, and impact of changes on merge ability. Do not Review or Merge.

### CODE REVIEW

**Comment by TheDuriel** [comment]
Several Scene files exceed the recommended maximum of 2MB. GIT will prompt elevation to LFS tracking for these files, however this should not be done.

**Comment by TheDuriel** [comment]
At this point the following folders remain to be cleaned:

- assets
- model_assets
- scenes

**Comment by Moonwards** [comment]
I am about to start a branch to import all the models fresh. Except for the two that have complex animations - AvatarRig and AthleteRover - they all now exist on the Moonwards-Assets repo but haven't been organized. The last two will be handled by Gyrth. 

I'll create the new folder structure in line with the Asset Pipeline doc.

They were all exported as gltf, which is a change in the pipeline. The export went fine, so I prefer to support that format

**Comment by TheDuriel** [comment]
I will finish my restructuring with the files at hand. You can then decide to remove and rebuild the world from scratch. Which would probably be a good idea. The file structure will be prepared for that then.

**Comment by TheDuriel** [comment]
This should be all.

As discussed, the World and Player related files are preserved in "Legacy" folders. Indicating that they are _to be replaced_.

Other parts of the project have been reorganized, and an example file structure for shared Assets and the Player have been provided. This structure can also be used for Actors.

This slightly deviates from the original proposed file structure, as it ended up making more sense overall given the nature of the project.

I've also included a new UserOptions system in the addons folder. Which can be used to automate the process of saving and loading user options, and helps syncing options across scenes. (Like with the username discussion from before.)

**Comment by Moonwards** [comment]
Ok, so the idea is the models and constructs that have been extensively changed can go in the Worlds folder, and once everything is hooked up properly, the contents of LegacyWorlds can be removed?

**Comment by TheDuriel** [comment]
Yes, both Legacy folders are meant to be frozen, and replaced piece by piece.

**Comment by Moonwards** [comment]
I've asked the dev staff to look at the conflicts and advise. I'm giving it some time for that.

**Comment by Moonwards** [comment]
@TheDuriel Are the changes listed as conflicts ones that are improvements?

**Comment by TheDuriel** [comment]
They're files I've moved or edited which we're also edited on Master. I'm in the process of sorting out the conflicts.

**Comment by TheDuriel** [comment]
Conflicting commits are 545570ac5ecf598ba1069dd9679361b640e6fe73

**Comment by TheDuriel** [comment]
#182 supersedes this.

**Pull request closed without merging**
