### PR TITLE
Tooltip Display smaller #645

### LINKED ISSUE #665: Make Tooltip text window stay the same size when the game window size is increased
This is so that more of the game world remains visible when a tooltip text is displayed.

### LINKED ISSUE #666: Reduce tooltip text size

### PR DESCRIPTION
**Pull request by Zach777**
resolves #666, resolves #665

### CODE REVIEW

**Comment by Zach777** [comment]
@Moonwards Is the Tooltip Display too small now?

**Review by Moonwards — CHANGES_REQUESTED** [review]
I changed the window to the size i like (which i thought i'd already pushed). 

The font size needs to come up maybe 2 points. 

This now covers the top right corner, so it commits us to moving the icons that were there to the bottom right corner.

**Comment by Zach777** [comment]
That change has already been made in exp/test-help-button

**Comment by Moonwards** [comment]
@Zach777  I think it would also be better to increase the size of the text in the buttons - in which case, the buttons also need to increase in size. There is room for that. 

Aren't people more used to Prev, instead of Last?

**Comment by Zach777** [comment]
Probably better to use Prev you are right.

**Review by Moonwards — APPROVED** [review]
The whole layout for this now looks good. Ready to merge.

**Pull request merged**
