### PR TITLE
Remap input and update Chat #788

### LINKED ISSUE #788: Reordering of keyboard controls
I'm going to propose some reassignments of keys for the default layout, as I have small hands and have never been all that good at using controls. With the suggested configuration, I never have to remove all my fingers from the keyboard or look away from my screen in order to use the controls. 

- [x] Have Q and 2 move the fly camera up and down
- [x] Move E to C
- [x] Have C do double duty - calling up the cursor when an interactable menu isn't available, and if one is, then both calling that up and the cursor at the same time.
- [x] Move 3 to R
- [x] The best way to call the cursor might be to use the right mouse button

### LINKED ISSUE #811: Update Chat help instructions. Add mouse instrucitons
The Ctrl + H chat instructions will need an update.

I think it would be good to include that the size of the chat window can be easily resized by dragging an edge with the cursor.

### PR DESCRIPTION
**Pull request by Zach777**
You will need to go into the controls settings menu and press set-to-defaults. The game will remember the settings from before because of the save file.

resolves #788 , resolves #811

### CODE REVIEW

**Comment by Moonwards** [comment]
I think this is working well.

Upon testing it, it occurred to me that a quick control to maximize and minimize the chat window size would be useful. How about switching that to just V from Ctrl V?

**Comment by Zach777** [comment]
@Moonwards Alright chat toggle size added to custom controls and switched to just pressing V.

**Comment by Moonwards** [comment]
@Zach777 One request - make the maximum size not overlap the info in the upper left corner? 

I like it that the horizontal size stays the width the user defines. I had thought to request that it also remember the height the user defines, but I think this approach is more useful.

**Comment by Zach777** [comment]
@Moonwards I mean, we could have it expand upwards to full and shrink to previous size.
 Then make hide chat a custom control and also quicker to press.

**Comment by Moonwards** [comment]
Hm....
I suppose for people who are following a chat conversation, that's what they'd really like to be able to do quickly. 
But I can also imagine people wanting to get it out of the way quickly - but still wanting to know right away if a chat message comes in. 

I dunno - should we create a quick access key for both?

**Comment by Moonwards** [comment]
It seems to me that having it stay minimized with one line visible is adequate, it doesn't take up much space and you can see who the message is from and such.

I'm totally good with a temp solution. In that case, leave it as it is. Because you can make the window as narrow as you like quite easily and adjust that quickly, it allows you to choose how much of the conversation is on your screen when you toggle. That's pretty good for now.

**Comment by Zach777** [comment]
@Moonwards Okay I setup Chat the way you requested. Let me know if anything else needs done.

**Comment by Zach777** [comment]
I updated this PR to also include resolution for #811 . I figured it would be best to combine the two since they are related in how they update Chat.

**Review by Moonwards — APPROVED** [review]
Smooooth

**Pull request merged**
