### PR TITLE
Fix lateral input moving character backwards

### LINKED ISSUE #822: HumanoidMovement moves backward slightly when strafing left or right.

### PR DESCRIPTION
**Pull request by yaelatletl**
Resolves #822

### CODE REVIEW

**Comment by Zach777** [comment]
Good stuff, Yael. What was the issue?

**Comment by yaelatletl** [comment]
the vectors used for moving in the x axis contained a bit of information for z axis, so i just discard any value that's under a threshold

**Comment by Zach777** [comment]
@yaelatletl I cannot move the character when I play the game.

**Review by Zach777 — CHANGES_REQUESTED** [review]
Fix the issue where I cannot move.
 Movement only works when I am aiming the camera a certain way.

**Comment by yaelatletl** [comment]
Alright, missed an abs() there, though thorugh testing I found out the behavior is not controlled by that specific part of the code, I even made it so inputs are exclusive (let's say moving in x disallows you to move in z and vieceversa) but the behavior is still there. There must be something I'm not seeing. Hm.

**Comment by yaelatletl** [comment]
Just happened to try that movement on a slope, it looks like it's not just backwards, it's the slope's direction

**Pull request closed without merging**
