### PR TITLE
Avatar settings persistent and networked #581

### LINKED ISSUE #581: Make color selector functionality saved and loaded on game restart
Hook up the color selector so that changes to the player's avatar are saved and loaded with the game.

Related to #582
Related to #566

### PR DESCRIPTION
**Pull request by Zach777**
Customization Settings are now persisted in `usr://Moonwards/avatar_settings.ini` 

Colors, usernames, and gender works. All networked.

resolves #581

### CODE REVIEW

**Comment by Zach777** [comment]
@Reousa Not entirely sure why you changed the title. The issue stores the settings locally, yes. But it also makes sure everything is networked properly too.

**Comment by Reousa** [comment]
@Zach777 Name just wasn't clear that's all, feel free to rename it as you see fit

**Review by Reousa — APPROVED** [review]
LGTM. Needs a QA pass

**Comment by Zach777** [comment]
@Reousa What does LGTM mean?

**Comment by Zach777** [comment]
@Reousa @Moonwards I rebased this branch onto master. Check that it works again and merge when ready.

**Comment by Moonwards** [comment]
@Zach777 Names don't display above the players.

**Comment by Zach777** [comment]
@Moonwards @Reousa I have nametags fixed again. Everything should be working now.

**Review by Moonwards — DISMISSED** [review]
Looks good!

I wonder about how the nametags decrease in size with distance. Clearly this is needed but visibility of the name drops quickly. Testers will need to say whether they can see names far enough away.

**Comment by Zach777** [comment]
@Moonwards I was thinking about this. What if the nametags increased in size, then disappear past a certain distance?

**Comment by Moonwards** [comment]
You mean, they don't shrink as fast, and they disappear past a certain distance?

Yes, i think that adjustment would really help.

**Comment by Zach777** [comment]
Okay I setup the nametags to stay the same size (and thus legible) but fade past a certain distance.
 Let me know how that looks.

**Comment by Zach777** [comment]
I don't know if my settings will have caused a regression with the pool occluding nametags. With how they are setup now, I don't think that the bug would be a big deal and might be appreciated by the player. Since you would want to see the pool and nametags would get in the way. Plus nametags are only visible above other people's heads.

@yaelatletl Could you add an npc to the pool area so that I can test nametag bugs more easily?

**Comment by Zach777** [comment]
Okay I tested the pool and the nametags. The black part of nametags gets occluded but the name is still visible.
 I actually think it works pretty great as it looks intentional.

**Review by Moonwards — APPROVED** [review]
This is even better with the changes.

**Pull request merged**
