### PR TITLE
Types and colors now display correctly with prop dropdowns

### PR DESCRIPTION
**Pull request by yaelatletl**

### CODE REVIEW

**Comment by Reousa** [comment]
What am I testing?

**Comment by Moonwards** [comment]
@yaelatletl I looked around in the NPC editor and couldn't find what this is referring to.

**Comment by Moonwards** [comment]
I see color picking causes the selected color to show in the Pick button. Is that part of this?

**Comment by yaelatletl** [comment]
Didn't see comments until today, this is a code fix for the nodes, which are color coded, so they change according to the type defined in the class they're inspecting (as dropdown is used for properties) 
For example, the intended use of the property_check:
imagen
This node setup wouldn't be quite like this before, having the output of the property_check node always set to ANY(white)

**Comment by Moonwards** [comment]
@yaelatletl the property_check output isn't green on the commit I've pulled. Is it supposed to be?

**Comment by yaelatletl** [comment]
> 
> 
> @yaelatletl the property_check output isn't green on the commit I've pulled. Is it supposed to be?

It starts as white, once you select an option from the dropdown it will change, green is for vector3

**Review by Moonwards — APPROVED** [review]
The colored pins connect properly with pins of the same color or white pins.

**Comment by yaelatletl** [comment]
That's correct, the white ones can be connected to any type

**Pull request merged**
