### PR TITLE
Add the ability to add "anchors" to game object, that players can anchor their position to.

### LINKED ISSUE #641: Create a system that allows nodes movements to be anchored in terms of movement
This is to allow certain nodes to follow the movement of nodes they aren't parented to.

This is supposedly available in some capacity in C++, for reference, but I could not find it in the docs.

### PR DESCRIPTION
**Pull request by Reousa**
Resolves #641

### CODE REVIEW

**Review by Moonwards — CHANGES_REQUESTED** [review]
The script is working well, including the fun option of pressing shift+F while driving the rover with the pod, and looking around in flying camera view.

The interface could be improved, as the first time i tried this, i didn't figure out how to use it because i wasn't playing in the expected way. I stayed in 3rd person, and moved quickly to the far end of the pod. In that situation, the signs in the bottom corner announcing interactables never had a chance to appear and i didn't see them. 

It works far better if you are in 1st person.

Now that i've tried it a few times there are other problems that i think will need solving before this is ready to merge

-  In a large part of the pod, if you grab a pole, you can't then activate the rover because the area to do that isn't viewable.
-  Once you've grabbed a pole, there is no way to let go.
-  There doesn't seem to be a way to exit after you are done, even if you are docked to an airlock

I imagine the first issue can be fixed by making the area that activates control of the rover is larger and visible from anywhere in the pod as long as you look at the pod's nose area. The second one also seems like an easy fix. The third one is maybe  a bigger deal.

**Comment by Moonwards** [comment]
I tried dismounting from the rover after holding a pole and mounting it, and the game froze.

Screenshot from 2020-10-14 13-05-03

**Comment by Moonwards** [comment]
There are a few details to look after

- `Grab a pole to stabilize your movement` shouldn't be one of the options on the InteractsMenu once you've mounted the rover
- The default `Press F to interact with Title` that appears when you are looking at the area for mounting the rover should be changed to something like `Press F to drive the Rover`
-  And a label should be added to the area for interacting with the rover - just a black square with the text 'drive rover'.

**Comment by Reousa** [comment]
@Zach777 could you add a texture to the `RoverRideRelay` interactable?
In reference to this:
> * And a label should be added to the area for interacting with the rover - just a black square with the text 'drive rover'.

File path: `res://Tree/Object/PassengerPod/PassengerPod.tscn`

**Review by Moonwards — DISMISSED** [review]
This is working fine and is now ready to merge.

**Pull request merged**
