### PR TITLE
Refactor player movement to use rigidbody

### LINKED ISSUE #510: Refactor player movement to use RigidBody
Refactor the player to use RigidBody, and give it a more realistic feel where applicable.

### LINKED ISSUE #527: Fix characters not moving along with the passenger pod, when inside it

### PR DESCRIPTION
**Pull request by Reousa**
Resolves #510
Resolves #527

### CODE REVIEW

**Review by Moonwards — CHANGES_REQUESTED** [review]
The player has great difficulty with inclines, and with going over edges.

Going down slopes, it switches into a flail animation very frequently. It should not enter that animation unless it is actually falling.

On edges it frequently gets stuck.

 It is not able to climb stairs other than the vertical stairs. I couldn't climb any of the other stairs I could access.

Note that most stairs in the game are much steeper than stairs on Earth. This is by design. Stairs might be at a slope of 70 or 75 degrees.

**Comment by Moonwards** [comment]
The player continues to not climb many stairs, and to easily get stuck. It may be worth asking @Gyrth about the approach he took to resolve this problem.

**Comment by Zach777** [comment]
What stairs do you mean? Vertical stairs or the ramps?

**Comment by Moonwards** [comment]
@Zach777 there are actually a lot more stairs than those two categories. It works now on ramps and vertical stairs. It can't use the stairs in the neighborhood, or to the passage to Center Atrium, or in the RecHab.

**Comment by Reousa** [comment]
I identified the problem, working on it

**Pull request merged**
