### PR TITLE
Add graphics settings #1028

### LINKED ISSUE #1028: Setup configurable graphics settings

### PR DESCRIPTION
**Pull request by Zach777**
resolves #1028

### CODE REVIEW

**Comment by Moonwards** [comment]
@Zach777 The low setting looks like the settings we had before. I've changed from Low to High and back, but it doesn't kick in. It never has the low spec look you showed us last week. I'm definitely on the right branch and have the latest commit.

**Comment by Zach777** [comment]
@Moonwards I tried changing how the system actually changes the graphics but have no luck. Also the changes needed does not improve performance at all compared to what it is doing now.

**Comment by Moonwards** [comment]
@Zach777 I think it is time to set this aside. It was worth a try.

We can return to the question of performance after we have the minimum tools we need to have user accounts needed for the contest.

**Comment by Zach777** [comment]
@Moonwards Can we go ahead and merge this PR just so I have the code in the project for later use?

**Comment by Moonwards** [comment]
@Zach777  Sure.

**Review by Moonwards — APPROVED** [review]

**Pull request merged**
