### PR TITLE
Add building app to Hud #571

### LINKED ISSUE #571: Building App HUD
This is in the GDD here:  https://github.com/moonwards1/Moonwards-Virtual-Moon/wiki/In-game-Building-App

The current draft is as follows:

And the initual mock up was like this - it included an object that depicted that stage of the process being done

### PR DESCRIPTION
**Pull request by Zach777**
resolves #571

### CODE REVIEW

**Comment by Reousa** [comment]
I wasn't able to test this, is it supposed to be working yet?

**Comment by Zach777** [comment]
Yeah clicking the left bottom button brings up the building app menu. All you can do is exit back to ToolsBar though.

**Review by Moonwards — CHANGES_REQUESTED** [review]
Looks good, but can we get rid of the numbers under the icons on the top menu? Although those icons indicate stages in a process, and different HUD tools appear in the bottom corner depending on which is active, i don't know how that could be communicated right now, or if it is worth spending time on at this point.

I like the subtle animations of those top icons. The highlighting of the bottom corner tools also works well.

**Comment by Reousa** [comment]
@Moonwards Give it a second QA run when you can

**Review by Moonwards — COMMENTED** [review]
This is working fine.

All the numbers should go, but if i understand correctly, the ones at the bottom are technically part of another scene, aren't they?

Doing more than this isn't necessary right now, i think this looks good and creates sufficient interest.

**Review by Moonwards — APPROVED** [review]

**Comment by Zach777** [comment]
All the numbers were removed.

**Pull request merged**
