### PR TITLE
Simulate Airlock #707

### LINKED ISSUE #707: Set up airlocks so that both doors can't be open at once
Unless a passenger pod (or other pressurized space) is docked, in which case both doors can be open.

### PR DESCRIPTION
**Pull request by Zach777**
QA checks: 
Test that airlocks openings are networked and that the simulation is played for everyone. Passed.
Test that client will have airlock synced even when the airlock is animating for other players. Probably passed. Might need more testing.

resolves #707

### CODE REVIEW

**Comment by Zach777** [comment]
Currently rebased onto feat/network-fixes so it is functional.

**Comment by Zach777** [comment]
@Moonwards Okay I have this setup where it simulates an airlock. I still need to add sound and a timer for simulating the time it takes for the air to come out.

 How long would it take for the air to be sucked out of the airlock?
 How long for putting the air back in?

**Comment by Zach777** [comment]
@Moonwards This is a fun QoL change for the airlocks. It feels really neat having the airlocks act like irl when getting into the Rover hatch.
 Should I add a sound effect for the airlock?

**Comment by Moonwards** [comment]
Yeah, it does feel good. 
A sound effect would really add something. Go ahead. I don't know what would be appropriate though. Bear in mind that this is an initial convenient version of the process. Really, the main noise should be air hissing into the airlock, but you wouldn't hear it at first because there is no air to transmit the noise through - it would get louder as the airlock fills up. For the same reason, when the outer door opens and closes there is no sound, because there is no air. Only the inner door would make a noise.

**Comment by Moonwards** [comment]
@Zach777 I'm sorry, I never saw before your earlier questions about times for air and all that. I try to follow PRs better now. The feeds and notifications I get aren't very helpful.

At this point, I think we can't include time for air to be pumped in and out. I could put a tooltip in an airlock about that, explaining what the process would actually be like. But we can't ask players to wait for several minutes for air to be completely pumped out of an airlock before the door opens, or even for 30 seconds for air to rush in.

**Review by Moonwards — APPROVED** [review]
Ready to merge. Addition of sound effect can go in another PR.

**Review by Reousa — CHANGES_REQUESTED** [review]
Needs a QA for network functionality first

**Comment by Zach777** [comment]
I feel like that would best be done under a separate PR. It would require a way to check if something is docked. Which means dockable things need to let the airlocks know that it is docked to them.

**Review by Reousa — APPROVED** [review]

**Pull request merged**
