### PR TITLE
Fix rocket display#698

### LINKED ISSUE #698: The Rocket Display isn't working
The text and buttons don't come up when it's activated. If you start it, then you are stuck.

### PR DESCRIPTION
**Pull request by Zach777**
resolves #698

### CODE REVIEW

**Comment by Zach777** [comment]
@Moonwards When you get a chance review this please.

**Review by Moonwards — DISMISSED** [review]
Yep, all better.

**Comment by Zach777** [comment]
@Moonwards Why did you dismiss your review?

**Comment by Moonwards** [comment]
I didn't... I don't know what action caused that. I did push a very minor change - it's loading the test scene right now, I set it to load the game. But now it isn't like that again, though I really thought I pushed that.

**Review by Moonwards — DISMISSED** [review]
All working
Just set it to load the game instead of the test scene

**Review by Reousa — APPROVED** [review]

**Pull request merged**
