### PR TITLE
Start Menu

### PR DESCRIPTION
**Pull request by Zach777**
Resolves issue section to be added later.

### CODE REVIEW

**Comment by Zach777** [comment]
@briligg @Reousa This branch is almost ready to merge. Can you two give it a look?
 The loading screen should be cycling images, but Godot freezes when it gets to a point loading I think. Thus the images quit cycling.

**Comment by Moonwards** [comment]
Yeah, I'll get to it before the end of the day. 

On a separate note, i might remove my briligg account from this organization so it doesn't cause any more confusion.

**Comment by Moonwards** [comment]
Do we really want to put the NPC editor directly in the Apps tab? Maybe it's better to do a layout like there is for Destination. For one, the editor doesn't have a lot of elbow room there, the logo and stuff is eating it up. For another, that would create the opportunity for people to select there from a list of NPC projects associated with their account. Some day. We could maybe mock that up.

The layout and format of what comes up in the settings menu needs a lot of work. I see some legacy stuff there that should by now maybe be completely removed from the project. Surely that code can't be used any more. 

The Visuals tab might need to be no more than a mock-up right now, in which case the aim is just nice, clear layout, and sliders and whatnot that will be easy and intuitive, once they actually work. And should we be saying Visuals there, not Graphics? 

The Controls tab is missing a lot of entries and also needs better layout. 

Strictly speaking, the heading tab for Destination should be highlighted green when the start menu loads.

The Avatar tab settings aren't saved. Is that being done as a separate issue / PR?

**Comment by Zach777** [comment]
@Moonwards 

I don't know why the NPC editor is there. We can remove it if wanted.

What needs changed in the settings menu? Controls is working. And graphics settings are just a mock up right?

All menus that focus on resolutions and game visual settings have been called a graphics menu from what I have scene.

Do you want me to make it where the control settings can change mouse controls? I would need to work on it quite a bit to make that happen. Godot's input API is lackluster in that regard.

A lot of the menu needs to be cleaned up responsiveness wise. Do we want to stick with the green highlights on lighter text?

Avatar changes should be a separate PR imo.

**Comment by Zach777** [comment]
QA testing:

Destination button above the main panel should be green at boot.
You should be able to switch between all main buttons.
You can start your own custom server.
(At this time, I have not tested join server. Might be worth a shot)
Backgrounds of Main Menu and Loading Screen cycle through textures in a random order.
Control settings remembers controls between sessions if you click save.
You can set controls back to project defaults.
You can quit the game from the Main Menu.

**Review by Reousa — APPROVED** [review]

**Comment by Moonwards** [comment]
My intention for the NPC app was that it can be opened from the Apps tab as its own environment. What the Apps tab is for, is allowing people to do that with any of the apps that will eventually be offered, so that instead of going into the full game, they can focus on work they are doing for the game. 

So that's why I think a layout like Destination would work for the App tab. One of the 4 windows that layout has could be the Building App, one the NPC app, one the Events app, and one the Film app. All except the NPC app button will be mock-ups. Clicking on the NPC app can open it full screen, but then that means there will at least need to be a way to return to the main menu. 

I don't know if that work fits here or should be moved into a separate issue and PR.

**Comment by Moonwards** [comment]
I see no need for mouse controls to be changeable. We just need a list of all the key controls there. 

Not M or F3, those can be dev secrets. But 3, Esc, Shift+ F, and the 1 and Q controls available when in flying mode.

 And little secrets like that you can use the arrows to advance or go back when you are in a tooltip or billboard.

**Comment by Moonwards** [comment]
I think the green of the tabs works. If anything, i'd darken the grey on the other tabs when they aren't highlighted, so it's easier to see the letters.

**Pull request merged**
