### PR TITLE
Add tooltips #365

### LINKED ISSUE #365: Make it possible to attach interactable 'cards' to objects - aka Tooltips
Set it up so that an area can be placed on or near an object that can be clicked on, and then a pop-up window appear with text, images, or a small video, or a sound clip plays.

It would be created as a 2d UI piece, that can be dragged and closed by the player.

There was a version of this that @SiudaPL wrote, and I believe @yaelatletl worked on this at one point early on. Possibly adaptation of some of that work would be advantageous.

To expand on how things will look, there will be two main visual parts:

* One is a 2d circle with an i or a ? inside of it, kind of like that button you find that opens the help page
this will be slapped on things in the 3D overworld, so perhaps a quad with a texture on it will do (it still needs to be clickable though, so Area)
 * The other is the tooltip its self, a 2d UI box that will contain content (images, text, video) and should be resizable and have an "X" button to close it

- [x] Create the UI that would be shown upon request
- [x] Create the tooltip object (interactable) that would be assigned data to be shown

### PR DESCRIPTION
**Pull request by Zach777**
resolves #365

### CODE REVIEW

**Comment by Zach777** [comment]
@Reousa Just as a heads up, the billboard effect for ViewportViewer does not SpatialMaterials built in Billboard enabled mode. Since the built in mode messes up ViewportViewer's button presses. I just rotated the root node of ViewportViewer to face the camera.

**Comment by Reousa** [comment]
What am I testing here, and can we add it to MTM? Couldn't find much when I ran it.

**Comment by Zach777** [comment]
@Reousa Okay everything is in working order. TooltipButton added to MoontownMaster

**Review by Reousa — CHANGES_REQUESTED** [review]
Can we have the collision be the same size as the actual texture, such as it doesnt display the animation before I hover over it.

**Review by Reousa — APPROVED** [review]

**Pull request merged**
