### PR TITLE
Building App buttons larger #603

### LINKED ISSUE #603: Building App tool buttons are too small
For ease of use the tool buttons in bottom right could be a fair bit larger - maybe a factor of  2 or so.

### PR DESCRIPTION
**Pull request by Zach777**
resolves #603

### CODE REVIEW

**Comment by Moonwards** [comment]
The buttons look good but they seem off center

Screenshot from 2020-10-27 20-38-02

**Comment by Zach777** [comment]
@Moonwards When you get the chance look at the menu again and let me know how it looks.

**Comment by Zach777** [comment]
@Moonwards Please review this when you get a chance.

**Comment by Moonwards** [comment]
My issue with this was that the icons in the buttons are stuck to one side of the button.

**Review by Moonwards — CHANGES_REQUESTED** [review]
Move the icons in the buttons to the right so that each one is in the center of its button.

**Comment by Zach777** [comment]
@Moonwards Done. Take a look when you get the chance.

**Review by Moonwards — APPROVED** [review]
Ah, the icons are larger now too. That's probably for the best.

**Pull request merged**
