### PR TITLE
Add AI & NPC Framework

### PR DESCRIPTION
**Pull request by yaelatletl**
Implemented the AI Steering Framework for seamless NPC navigation.
Implemented a Workstation/worker model with optional XP system. 
Implemented a Navigation and objective manager that assigns wokrstations to NPCs that request it. 
Added functions to allow the use of new commands in the Behavior Tree Editor. 
Added a new special label to the Behavior tree editor, that allows to select elements from an enum
Implemented an integrator to manage signals from components of an NPC and contain the MwNPC.gd node. 
Added example Behavior tree.
Changed the way dialogs get their display name if the dialog is triggered by an NPC. 

From tracker #507:
# Basics
- [x] Can navigate the world
- [x] Interacts with players and other NPCs (subtracker)
- [x] Organic movement
# World Interaction system
- [x] Objective system and workstations, give the NPCs places to visit and things to do
- [x] Workstations have a inner progress counter, so the NPCs knows when it has has to go and do other stuff
- [x] Stablish if the NPC will be available to talk when in a workstation (done in behaviors)
- [x] Workstations have been placed 
Note: A worksation isn't necessarily a work place, it can be a spot in the swimming pool or in a table
- [x] Implement functions for such interactions inside MwNPC.gd
- [x] Interactions, make NPCs interact with each other

### CODE REVIEW

**Comment by Reousa** [comment]
@yaelatletl can you give it a rebase?

**Comment by Reousa** [comment]
@yaelatletl status on this?

**Comment by yaelatletl** [comment]
Status: integrated NPCs and almost nailed Workstations, but navigation is making testing those kinda difficult, NPCs no longer move correctly following the rebase

**Comment by Reousa** [comment]
Closing this, now tracked in #668

**Pull request closed without merging**
