### PR TITLE
NPC Editor moved to Hud #580 #579

### LINKED ISSUE #579: Move 'NPC Editor' menu entry inside of 'Apps' section - part of #566
Instead of being part of the initial start menu, `NPC Editor` should be a heading in the submenu shown when the `Apps` menu button is clicked.

The display of the editor interface should also open on load of the game, as an overlay, if the submenu button for it is clicked under Apps.

To make that more workable, the appearance of that interface should change, as described under issue #580

### LINKED ISSUE #580: Change appearance of NPC editor interface in-game - part of #566
The quick solution here would be to change the background to the blurred background Hevedy made, define the borders of the node area with a line, and make the buttons match other UI elements - white on a black background with alpha of 0.7 or so.

### PR DESCRIPTION
**Pull request by Zach777**
resolves #580 
resolves #579

### CODE REVIEW

**Comment by Zach777** [comment]
@yaelatletl Please take a look at Hud scene. The button on the bottom second to the right in Hud.tscn is NPC editor.

**Comment by Zach777** [comment]
@Reousa Okay I have the functionality ready to go. There is some refactoring needed with how the scenes are setup though. Do you want me to go ahead and refactor now or get this PR merge ready and create a new issue later?

**Comment by Zach777** [comment]
@Moonwards @yaelatletl @Reousa This PR is ready for review.

**Comment by Reousa** [comment]
What am I testing here?

**Comment by Zach777** [comment]
@Reousa Hud scene npc editor button. Then let me know what needs fixed with the npc editors theme.

**Review by Reousa — CHANGES_REQUESTED** [review]
It's still it's own thing, not inside the "App" section

**Comment by Zach777** [comment]
@Reousa It should be on the bottom button second to the right? Is it not?

**Comment by Zach777** [comment]
@Reousa Please merge this. The icon second to the right on the bottom row brings up the npc editor menu.

**Review by Reousa — APPROVED** [review]

**Pull request merged**
