### PR TITLE
Main Menu App grid layout

### LINKED ISSUE #684: Main menu - change Apps tab menu layout
Instead of having nested tabs, the Apps tab would look better with the layout of the Destinations tab. 

The four Apps i'd list would be Building, NPC, Events, and... maybe Library.

The icons already available for them can go in the center of each box.

Related to this, the NPC editor should open in its own window if selected in the App tab. That's Issue #685

### LINKED ISSUE #685: If NPC editor is chosen in Main Menu Apps tab, opens in own window
Exactly how this should work right now bears discussing, but at any rate the NPC editor really needs its own window if one is going to use it properly.

In the longer term, the idea of having these apps available from the main menu, in addition to in the game, is to allow you to focus just on what you are doing with the app. Ideally, you could work in the app without actually being present in the game.

### PR DESCRIPTION
**Pull request by Zach777**
resolves #684 , resolves #685

### CODE REVIEW

**Comment by Zach777** [comment]
@Moonwards Let me know if you want me to make the App buttons have the same color as the Destination buttons. I don't know why they decided to be a different color but they are.

**Comment by Moonwards** [comment]
You've had a few problems with colors in the menu, eh? Weird.

Yeah, it would be better if they were the same color, and also translucent the same way. @Zach777

**Comment by Zach777** [comment]
@Moonwards Alright fixed the issue with buttons having different colors in different tabs. Check it out when you get the chance.
 Let me know if I should darken the buttons or if the colors are off compared to what they were before.

**Comment by Moonwards** [comment]
The tabs look consistent and the colors are good. That makes this ready to merge, right?

**Comment by Zach777** [comment]
Whenever Karim wants to merge

**Review by Moonwards — APPROVED** [review]

**Pull request merged**
