### PR TITLE
Hooked up the resolution setting to a function that applies it.

### PR DESCRIPTION
**Pull request by Gyrth**

### CODE REVIEW

**Comment by Gyrth** [comment]
We still need a way to apply the resolution once the user restarts the application. Anyone have an idea on how to accomplish this.
Related to #45

**Comment by Gyrth** [comment]
In my own project I just write to the ProjectSettings file. And once the game is exported an external engine.cfg is created next to the executable. So once you write the width and height of the resolution it automatically applies that the next time the application starts. But I'm not sure if this is the correct way of doing it.

**Comment by Gyrth** [comment]
Did GH just added these commits automatically? Or did you do that @TheDuriel ?

**Comment by TheDuriel** [comment]
@Gyrth Those looke automatic. Pull requests are specific to the branch, so if you update your branch it should update the PR.

**Comment by Gyrth** [comment]
Ah nice. So I should create a new branch from master for each feature I suppose. Then create a pull request once it's ready.

**Comment by TheDuriel** [comment]
Yup. All good to merge?

**Comment by Gyrth** [comment]
Yes.

**Pull request merged**
